development:
  sessions:
    default:
      database: unitedway
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: unitedway
      hosts: 
        - 172.31.42.138: 27017